services:
  mlflow:
    build: .
    command: >
      bash -c "mlflow db upgrade sqlite:///mlruns/mlruns.db &&
               mlflow server \
               --backend-store-uri sqlite:///mlruns/mlruns.db \
               --default-artifact-root ./mlruns \
               --host 0.0.0.0 \
               --port 5001"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"

  streamlit:
    build: .
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001